### ISSUE TITLE
How do Solve this Issue in Replit

### ISSUE THREAD

**Issue by MrDiscordAnimation** [replit-discord/Replit.sh-v4#1]
In the Console It's Show this:
events.js:353
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_http_outgoing.js:694:15)
    at ServerResponse.end (_http_outgoing.js:815:7)
    at /home/runner/Replitsh-v4/index.js:56:70
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:753:7)
    at processTicksAndRejections (internal/process/task_queues.js:83:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}
Can Anyone Help me?

**Comment by MrDiscordAnimation** [comment]
Sorry I sen in the wrong issue

**Comment by MrDiscordAnimation** [comment]
I accidentally Click Close the issue

**Comment by piemadd** [comment]
Can you share a link to the Repl you're using this in?

**Comment by piemadd** [comment]
Im closing this due to no response.
